### ISSUE TITLE
Game page achievements not showing number of winners

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#17] opened 2018-02-14 01:04 UTC
On the game pages some achievements are not displaying the number of earners:
![image](https://user-images.githubusercontent.com/32706333/36182244-e2bfbd1a-10e5-11e8-8780-8179a21de8f1.png)

Why is this happening?
There are earners on the list that don't have an account.
-- I know this is the problem here for ~Bonus~ Star Fox 64, as I made typos while manually awarded achievements to players therby giving points to players which do not exist.

http://retroachievements.org/Game/10630, http://retroachievements.org/Achievement/57625, 
Also see "Phantom Penance" http://retroachievements.org/Game/1447.

There may be a second issue that has something to do with untracking, this is when this problem started appearing.
http://retroachievements.org/Game/1701

**Comment by meleu** [comment] 2018-06-10 02:52
note for self (or anyone else interested in solve this): the problem is in [this SQL query](https://github.com/RetroAchievements/RAWeb/blob/f2fd50f5f4a25e7739bb45bd01ebf54d66953213/lib/database/game.php#L177). I'll try to fix it when I have a chance.

**Comment by anegoda1995** [comment] 2021-11-21 02:23
Seems it was fixed, because now I don't see this problem. I think it will be good idea to close this issue.

**Comment by luchaos** [comment] 2021-12-08 03:44
Indeed, this has been fixed quite some time ago. Closing

**Closed by luchaos** 2021-12-08 03:44 UTC
Labels: bug, game page
