### ISSUE TITLE
Dockerfile for dev environment

### ISSUE THREAD

**Issue by jeresch** [RetroAchievements/RAWeb#222] opened 2018-09-19 16:47 UTC
Hi, I'd love to help out with development, but I'd like to keep my local machine as clean as possible (without php libs, database, etc.).  I'd prefer not to use a full VM using Vagrant.  Is there still a plan to put together a Dockerfile for a development setup?  It is mentioned [here](https://github.com/RetroAchievements/RAWeb/wiki/Getting-Started#development-environment-setup-1).  I can try to set one up if that'd be helpful.

**Comment by jeresch** [comment] 2018-09-20 16:46
I'm working on a Vagrant setup, but I'm a little confused with the intended setup.  Is the develop branch using Laravel now?

**Comment by meleu** [comment] 2018-09-20 19:10
hi @jeresch , it's good to see people wanting to contribute with actual code for the website. But the laravel branch currently is not publicly available.

Undoubtedly the site got many improvements and fixes for historical bugs since @ScottFromDerby opened the source. But as we are seeing some clone sites popping around, now we are in a more conservative posture (yeah, the wiki is outdated).

We plan to find a way to allow contributions later, but it's not a high priority at this moment.

I hope you understand and don't lose your interest in contributing to this project.

And if you want to stay in touch with the staff, I invite you to join our [discord server](https://discord.gg/dq2E4hE).

**Comment by jeresch** [comment] 2018-09-20 19:40
Shoot, that's disappointing.  Okay, well I look forward to when you open it up in the future.  I'll try to get on the discord server too.

**Comment by luchaos** [comment] 2018-11-02 10:17
duplicate of https://github.com/RetroAchievements/RAWeb/issues/44
closing

**Closed by luchaos** 2018-11-02 10:17 UTC
