### ISSUE TITLE
API Issues with Retrieving User Data

### ISSUE THREAD

**Issue by HankChill** [RetroAchievements/RAWeb#421] opened 2020-02-09 02:05 UTC
I've discovered a couple API issues with RetroAchievements.

- There seems to be a max URL request length on the site now. I used to be able to send a request for game progress data for a user providing hundreds of game ID's in the request, and now I get a 414 URI exceeds request length. When a new user tries to add their user account on CheevoTracker it fails now.
- GetUserRecentlyPlayedGames is returning nothing now. Recently I noticed issues with it, where it would return the recently played games, but no achievement progress for that game for the user. Now it returns nothing. Did this API change?

Has there also been any progress with creating an API that will only return games that have achievements? For a long time now, when retrieving a game list for a console ID, every single title is returned, and each game has to be processed one at a time to see if it has achievements. A lot of time (and site/database hits) can be saved in the API was expanded to only return games with achievements.

**Comment by webdevkit** [comment] 2020-02-10 16:05
The 414 URI error sounds like a server configuration issue. I've only just started reviewing this repository, so I don't know much about it, but if it is an nginx server, then [we might need to update a couple of configuration properties](https://stackoverflow.com/questions/1067334/how-to-set-the-allowed-url-length-for-a-nginx-request-error-code-414-uri-too).

I have a PR #423 that includes an example of how to get the list of games with achievements in order to update the game list counter on the main page. I'm still trying to wrap my head around the architecture of this project and API and I haven't had any discussion with the project owners yet so it might be better for me to hold off on making more changes.

**Comment by luchaos** [comment] 2020-03-13 15:47
There are several issues in this one :)

Are you sure it was 'GetUserRecentlyPlayedGames`, not `GetUserSummary`? The latter had a bug which should be fixed now. If it's still about the recently played games - I cannot reproduce any erroneous responses - is it bound to specific users for you?  

About the 414 error - i don't think it's a good idea to increase the query length limits as the database server already struggles with the amount of non-optimized queries. Would it be possible to do multiple "paginated" requests instead?

> Has there also been any progress with creating an API that will only return games that have achievements? For a long time now, when retrieving a game list for a console ID, every single title is returned, and each game has to be processed one at a time to see if it has achievements. A lot of time (and site/database hits) can be saved in the API was expanded to only return games with achievements.

That is good input! I'll see what i can do there. Adding the core achievement count to that endpoint should be easy enough .

**Comment by hankchillx** [comment] 2020-03-14 01:05
Thanks for the update @luchaos -- I'll double check the API that I'm using for the user's recently played games. If I am using GetUserRecentlyPlayedGames, I'll change it over to GetUserSummary.

Regarding making paginated requests, I can definitely do so. It's only a one-time deal so if it has to take a few extra seconds to make a couple more requests, I don't see any harm in that. Currently, what is the max URL length allowed? I can code around that to ensure I don't go over the max request length.

For the retrieving of games that have achievements, I assume my following request will most likely require an additional API as currently no existing API features this, but could the API for retrieving game data be extended to allow a list of game IDs, rather than a single ID? It would (hopefully) be less taxing to provide a list to retrieve and get all the data for a group of games back at once, rather than make many separate API calls to the endpoint in succession to retrieve a large amount of data. I'm holding off on automating a service to retrieve the games/achievement listing on my app as I don't want to make thousands of API calls a day, but rather:
1 API call per console -> Retrieve the list of titles for that console, and drop any titles with 0 achievements.
1 API call for titles per console -> Retrieve all of the provided title ID's, and their associated details and achievements (can potentially be 2 or 3 calls for consoles that contain many supported titles)

I understand if the request isn't feasible due to potentially serving back megabytes of text (for consoles like SNES and NES which have hundreds of supported titles with achievements), but hey a guy can dream right ;)

**Comment by meleu** [comment] 2020-03-14 01:26
> (...) API that will only return games that have achievements?

You can get it via `dorequest.php`, like this:
`https://retroachievements.org/dorequest.php?r=officialgameslist&c={CONSOLE_ID}`

And you can see valid console IDs here:
https://github.com/RetroAchievements/RAWeb/blob/develop/lib/database/release.php

**Comment by meleu** [comment] 2020-03-14 02:15
@webdevkit 
>  I'm still trying to wrap my head around the architecture of this project and API and I haven't had any discussion with the project owners yet so it might be better for me to hold off on making more changes.

I'm currently working intensively with Node.js and tripping down that rabbit hole, hence with not enough freetime to make the changes and properly test before submitting a PR...

But if one of you guys (or even @MrOwnership) would like to make the `API_GetGameList.php` return only the games with official achievements, maybe a good way would be something like this:

### 1. In [lib/database/game.php](https://github.com/RetroAchievements/RAWeb/blob/develop/lib/database/game.php), specifically in the function [getGamesList()](https://github.com/RetroAchievements/RAWeb/blob/develop/lib/database/game.php#L460)
```php
function getGamesList($consoleID, &$dataOut, $officialFlag = false)
{
    $dataOut = getGamesListData($consoleID, $officialFlag);
    return count($dataOut);
}
```

### 2. In [public/API/API_GetGameList.php](https://github.com/RetroAchievements/RAWeb/blob/develop/public/API/API_GetGameList.php)
```php
// ...
$consoleID = seekGET('i');
$officialFlag = seekGET('o');
getGamesList($consoleID, $dataOut, $officilFlag);

echo json_encode(utf8ize($dataOut));
```

Those changes should make it possible to get only the games with official achievements by calling `API_GetGameList.php` with a non-falsy value as an argument for `o` (such as `o=1` or `o=true`). I think it'll be enough to add such feature and keep backward compatibility.

**Comment by meleu** [comment] 2020-06-08 13:03
> Has there also been any progress with creating an API that will only return games that have achievements?

I've just did it in https://github.com/RetroAchievements/RAWeb/commit/6e88f1812d62061e717309c013b9a4b29e41db17

You just have to add `f=1` to the query.

**Comment by luchaos** [comment] 2023-12-16 16:33
I have to assume this is not an open issue anymore, a lot has changed since then.
Please refer to https://api-docs.retroachievements.org/ for more information, or if this issue still should be looked at, please open a new one 🙏

**Closed by luchaos** 2023-12-16 16:33 UTC
Labels: kind/bug, area/api-web
