### ISSUE TITLE
Tickets are displaying "No other tickets found..." when it's not true.

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#1818] opened 2023-09-02 21:38 UTC
**Describe the bug**
Some achievements with multiple tickets are showing "No other tickets found for this achievement"

**To Reproduce**
Just one example:
https://retroachievements.org/ticketmanager.php?i=43226
https://retroachievements.org/ticketmanager.php?i=54113

**Expected behavior**
It should show the total number of opened/closed tickets for that achievement and links via ticket IDs.

**Comment by MSGoodman** [comment] 2024-01-07 06:30
Unless I'm looking in the wrong place (very possible!), the links provided no longer appear to display this behavior:
<img width="1188" alt="image" src="https://github.com/RetroAchievements/RAWeb/assets/10148380/cde89156-0127-47a2-8f8f-effba9ac8a01">


 Can you point to another instance of this happening so we can try to figure out the cause?

**Comment by wescopeland** [comment] 2024-01-07 16:58
Here is the most flagrant demo of the issue I can find on prod: https://retroachievements.org/ticketmanager.php?i=50158

There are 4 tickets assigned this achievement, however clicking into each one shows something bizarre in that table row.

The 4 tickets are:
* https://retroachievements.org/ticketmanager.php?i=58506
* https://retroachievements.org/ticketmanager.php?i=50158
* https://retroachievements.org/ticketmanager.php?i=48372
* https://retroachievements.org/ticketmanager.php?i=31296

**Comment by MSGoodman** [comment] 2024-01-09 06:41
Interesting. It's the same ticket that's missing from all of the others, which feels like a clue...

Do we have any way of cloning non-sensitive (probably most if not all?) prod data down to a test env? Or a way of accessing prod data via read-only? I feel like it'll be hard to diagnose without being able to really poke at that stuff.

**Closed** 2024-03-28 14:07 UTC
Labels: kind/bug, area/back-end, good first issue
