### ISSUE TITLE
Recently players list looks more barren than it should

### ISSUE THREAD

**Issue by mosquitobird11** [RetroAchievements/RAWeb#1225] opened 2022-11-11 08:52 UTC
https://github.com/RetroAchievements/RAWeb/blob/dcce0306e2d623a32812179dd7398be7986923f7/lib/database/player-game.php#L346

Because this line is joining only on `ua.LastGameID` (presumably because rich presence message only exists for the last game played?) many game activities look very barren and gives off the impression that the community is not as active as it really is. I suggest that until v2 DB changes exist and allow multiple rich presence, that this join be on `App\Community\Models\UserActivity`.`subject_id` WHERE type is `UserActivity::StartedPlaying`. 

This would sacrifice rich presence text in the list at the benefit of a more populated list, which seems like it would be more useful in its current state. It can feel void when I load a list for a game I like to see that only "4" people have played it this year, and it can be confusing to see a game recent player list that I know I have played recently but I do not appear in the list.

**Comment by Diskutant** [comment] 2023-02-10 17:51
I just realized the "Recent Players" list is more like "a list of players who didn't play anything else after this game".
I think that's what this issue is about. 
I agree that loosing the Activity of the recent players list would be sad, but getting a more realistic list of recent players is more important I think.

**Comment by redwizard42** [comment] 2023-02-10 17:53
Even if it could just cache the most recent 20 or so players, that would be nice.

**Comment by Soulsderfuchs** [comment] 2023-02-10 21:24
This is exactly how is inteended to be, maybe more so it shouldn't be named recent players but instead Current Players as this is the actual statistic worth showing and not people that are not even playing the set anymore.

**Comment by Diskutant** [comment] 2023-02-11 07:26
The way it is now, those lists are mostly filled with players who don't play anything at all anymore ie. inactive users.

But if that's the intended behavior, how about adding a tab where we could switch between the list as it is now, and a true list of recent players? For some very popular games those two lists might look almost identical, but for like 95% of games this would be an additional and (to me) very interesting information.

**Comment by redwizard42** [comment] 2023-02-11 12:39
It may be intended, but it looks barren in many cases. Site is likely to look better if more players show up in a list of players.

**Comment by Jamiras** [comment] 2023-02-11 13:24
It's not intended so much as a limitation of the data. We currently only keep one rich presence string per player, so they can only appear in whatever one game they have most recently played.

As suggested in the first post, we could leverage the activity table to find some other recent players, but they wouldn't display any rich presence information, which is a big part of the recent players list.

**Comment by Jamiras** [comment] 2023-11-03 12:41
This should be fixed with v5.1 (#1932). Rich presence will now be stored for a period of time even after a player moves on to another game.

**Closed** 2023-11-11 18:14 UTC
