### ISSUE TITLE
Amount of games in the Statistics sections isn't accurate

### ISSUE THREAD

**Issue by Maximdraco** [RetroAchievements/RAWeb#1400] opened 2023-03-02 01:16 UTC
Like the title said, in the Statistics section of the main page it says (at the moment I post this) than there are 6535 games (with sets I assume) but in the list of games with sets says there are only 6145 games.

Is for subsets or hubs?

**Comment by Jamiras** [comment] 2023-03-02 01:21
No, it's just counting games with achievements. The 6535 is all games with achievements. The 6145 is games with published achievements. That means there are 390 games with achievements only in Unofficial.

**Comment by wescopeland** [comment] 2023-03-02 01:40
Duplicate of https://github.com/RetroAchievements/RAWeb/issues/1356

**Comment by wescopeland** [comment] 2023-07-15 13:37
Closing as a duplicate of https://github.com/RetroAchievements/RAWeb/issues/1356. I will add Jamiras' insight to that issue.

**Closed by wescopeland** 2023-07-15 13:37 UTC
Labels: duplicate, where/home
