### ISSUE TITLE
Profile Page Keeps Dumping Active Playing Game (Affects RA Tracker App)

### ISSUE THREAD

**Issue by Chromagram** [RetroAchievements/RAWeb#2590] opened 2024-08-04 10:10 UTC
**Describe the bug**
The "Last 5 Games Played" section keeps intermittently removing my currently playing game for several minutes from the list. As a result, my RA Tracker app keeps seeing an unrelated game as "Active".

**To Reproduce**
Two ways to view this (if you want to see the extent of the issue, try all steps. But you can get the general idea just from doing the first step and reading the other steps)

1. Go to a user's Profile page (preferably one that is actively playing a game at the moment). Keep refreshing while they're playing and see if the game they are playing gets removed off the list entirely.

2. [This app](https://github.com/Colossus-Gaming/retroachievements-layout-manager) uses an API to track your most recent game and generates a list of that game's achievements, along with tons of other useful metadata for OBS. If you want to see the extent of the issue, download this app, login with your RA account, try playing a game for a bit. Whenever RA dumps an active game temporarily from the Last 5 Games Played list on your Profile page, the app has no choice but to assume you stopped playing it and sets the next game in the list as active, instead of the game you are actually actively playing.

**Expected behavior**
If I am actively playing a game (in my current case, Mario Party 1 on N64), RA should keep that game in my 5 Most Recently Played games list no matter what. This would also keep the app tracking the correct game.

**Screenshots**
![Correct](https://github.com/user-attachments/assets/2ba489c7-f38d-4fda-a9fa-f609badc0ce0)
![Incorrect](https://github.com/user-attachments/assets/2a19a789-f9fe-4925-93bc-a934a47cdfef)
I took these 2 screenshots during my stream tonight. The first screenshot is when RA is correctly showing Mario Party at the top of my recently played games on my profile page.
The second screenshot is whenever RA randomly removes Mario Party from that list. The next game I most recently played takes over at the top, and the tracker app automatically starts tracking that. (in my case, Animal Crossing on GameCube)

**Desktop (please complete the following information):**
 - OS: Windows 11 (23H2, 22631.3958)
 - Browser: Google Chrome (127.0.6533.89, Official Build, 64-Bit)

**Additional context**
I also have captured footage from tonight stream showing the problem happening, at least from the tracker side.
https://www.twitch.tv/videos/2215340820

The VOD is over 5 hours long, so please view around 03:07:10 as the timestamp. You can see the tracker on the left side, tracking the correct game and displaying the appropriate data. All of a sudden, it just loses the game and switches to Animal Crossing instead. Whenever this change occurs, if you visit your profile on the RA site, my active game (Mario Party) is not even on the Recently Played Games list. The game I last played before it takes over (Animal Crossing). This ultimately does recover by itself after several minutes. However, this issue does occur multiple times every stream recently, and other viewers have chimed in saying they've seen other streamers with the same problem.

The reason I am reporting this to RetroAchievements and not the app dev is because the app just takes a user and uses their WebAPI to pull data that the site gives it. If the RA site doesn't automatically unintentionally dump the active played game from the list, this issue does not occur. This needs to be examined on the RA side.

Thank you for reading this, I hope I provided enough info. This has been a pretty annoying and weird bug as someone who almost strictly streams playing for RAs. I hope it gets resolved soon. If I can help with any more info, please let me know.

**Comment by wescopeland** [comment] 2024-08-04 11:53
Hi! Do you have a rough idea of when this issue started happening?

**Comment by wescopeland** [comment] 2024-08-04 12:14
No worries. A few other things I want to rule out:

* When the issue occurs, did you happen to have two emulators open at once, even if on different devices?
* When the issue occurs, does it always pop back to a GameCube game?

**Comment by wescopeland** [comment] 2024-08-04 12:16
I also want to make sure I'm reproducing the issue correctly. At the moment, Olafur is playing Super Smash Bros. Melee:
https://retroachievements.org/user/Olafur

I've been refreshing for about 10 minutes and haven't seen the issue come up. Is this something happening regularly, or only at intervals spaced between a few hours?

**Comment by wescopeland** [comment] 2024-08-04 13:32
I believe I've determined the root cause of the problem.

We recently made some changes to how we're tracking user activity. As of last Thursday, we've started tracking what hash you're using when you start a game, unlock an achievement, or submit a leaderboard score. This is all to help us better understand how people use RetroAchievements and give us better insight into problematic hashes that are attached to games.

My theory is this bug is happening roughly around the time you participate in a game leaderboard. That would explain why this came up after I watched Olafur for around 10 minutes. Smash Bros has hundreds of leaderboards.

The code we have to update your "last played games" explicitly expects us to send a timestamp. When we record the session data for leaderboard stuff, we forgot to pass in the timestamp. The server assumes this is intentional and erases it.

**Comment by wescopeland** [comment] 2024-08-04 14:31
Sure thing! It'll be a while until the fix goes out, probably a couple of weeks.

When the code has been reviewed and merged, this issue will automatically be closed.

Once the code is actually deployed, I'll ping you in this issue asking you to keep an eye out.

If the issue resurfaces after the fix is deployed, let us know and we can reopen the issue.

**Closed as completed** 2024-08-07 13:25 UTC
Labels: kind/bug, area/back-end

**Comment by wescopeland** [comment] 2024-08-08 13:18
@Chromagram The fix for this issue how now been deployed - please let us know if it's still happening!

**Comment by wescopeland** [comment] 2024-08-11 13:06
Great! Thanks for the follow-up.
