### ISSUE TITLE
[Bug] [Minor] [User-Profiles] "Last X games played" list missing information when game search is widened

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1403] opened 2023-03-02 14:26 UTC
Taking the idea of "Last X games played" list from [this forum post](https://retroachievements.org/viewtopic.php?t=20586&c=156967#156967) mentioned by user [GregHouse007](https://retroachievements.org/user/GregHouse007), I noticed something weird which is something that exists since V1 in 2020 and wasn't fixed yet. However, due its nature, now I wonder if this was made to save server bandwidth and improve page loading performance at the time due to server's bandwidth being not so strong like nowadays **OR** if this is really a valid bug since it wasn't intentional.

**Try yourself:**
1. Go to any valid profile on RA Website. If you played a lot of sets, you can try this on your profile instead.
2. Widen your search for "Last X games played" to list more than 5 games
3. If everything stays normal, try to widen more and more...
4. At some time, some existing sets whereas the user didn't get any achievement on it, will show no achievement thumbs as expected sounding that the set doesn't exist. A text like "0 of X achievements" can be seem, but no achievements will be loaded. Sometimes, some achievements will load, but not all of them. Example: Set has 102 achievements, but only 55 loads on profile.

Another thing noticed is: In case of incomplete achievement loading, only ones that you already obtained will be loaded. Others locked will be "discarded" from loading routine. However, the more you widen your search, the more you get a chance of seeing achievements that you won in Hardcore Mode being presented as they were obtained in Softcore Mode: without that yellow squared border on an achievement. I only play games on Hardcore Mode!

- Example showing [Show do Milhão](https://retroachievements.org/game/125) and [Castle of Illusion](https://retroachievements.org/game/9) sets. Notice the yellow squared border being absent on all achievements on Show do Milhão and only the last achievement on Castle of Illusion being marked as Hardcore. That last achievement of CoI was obtained after 1 month after its previous achievement.

![](https://i.imgur.com/6SsBFaS.png)

- A view from [Show do Milhão](https://retroachievements.org/game/125) set highlighting that achievement showed on previous image was actually obtained in Hardcore Mode, not in Softcore like the Flash Card shows there.

![](https://i.imgur.com/4TDQ2yR.png)

- Another example of this bug happening: this time on [Flicky](https://retroachievements.org/game/59) and on [Robotnik Mean Bean Machine](https://retroachievements.org/game/209) sets. Robotnik MBM set wasn't mastered at the time (2019). So, the last 2 achievements that are locked on set are not shown there. Everything is marked there as Softcore when the progress bar says "Mastered" like the first image above.

![](https://i.imgur.com/4Rgcoj5.png)

**Expected behavior:**
At first view, the result expected was to load everything right regardless of how widen your search for lastest games is unless if this was intentional.

**Referenced Profiles:**
[Last 1500 games played by Kaizard (only 141 possible will be listed)](https://retroachievements.org/user/Kaizard?g=1500)
~~[Last 150 games played by GusStreamBR (this will list every game in range - and, yes, this user resetted their profile)](https://retroachievements.org/user/GusStreamBR?g=150)~~ [User **deleted** their account in March 2023]
[Last 1500 games played by me (only 103 possible will be listed)](https://retroachievements.org/user/Alexdatadestroyer?g=1500)

This is an old bug and I couldn't find it reported anywhere on this repository. If this is a duplicated case, my apologies!

**Exception Level: Medium** -- Only happens when the player has played a lot of games!

**Comment by wescopeland** [comment] 2023-04-17 12:42
I suspect this is the cause: https://github.com/RetroAchievements/RAWeb/blob/f10b6de412052f16387fb4f28ce62e68bf724fbe/app_legacy/Helpers/database/player-achievement.php#L197

When the limit is hit, I think some achievements are being truncated from the response, which is why it appears some achievements are missing as soon as the count is set to 166, but not 165.

Increasing the limit may not be the most efficient solution, as it may cause the query to return too many results, especially if the number of game IDs continues to grow. A better approach might be to implement pagination so that the results can be fetched in smaller, manageable chunks.

**Comment by luchaos** [comment] 2023-10-30 19:41
Resolved with v5?

**Comment by Alexdatadestroyer** [comment] 2023-11-02 07:31
> Resolved with v5?
> 
> **-- luchaos**

I made a Test Case with 5000 games (?g=5000) and used my example posted at the time (?g=1500) and this issue seems to be solved! However, I found another problem, but I dunno if this was expected to happen or not as shown below:

![](https://i.imgur.com/1MxffvQ.jpg)

![](https://i.imgur.com/YXIHXke.jpg)

When the list goes to accessed games only - meaning that I didn't win any badge since - this happens: **The "Last played" field is null.** This behavior goes until the end of the list.

**Comment by luchaos** [comment] 2023-12-17 17:13
> this issue seems to be solved! 

Fantastic! closing this one then.

> However, I found another problem, [...]
> When the list goes to accessed games only - meaning that I didn't win any badge since - this happens: **The "Last played" field is null.** This behavior goes until the end of the list.

I see - can you please open a new issue for the "Last played" issue?

**Closed by luchaos** 2023-12-17 17:13 UTC
Labels: where/user-profiles
