### ISSUE TITLE
News posts can break the home page

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/RAWeb#2144] opened 2024-01-09 23:57 UTC
**Describe the bug**
It is possible to create news posts with invalid HTML, ultimately breaking the home page. Over the last year, this has occurred at least 3 times that I can remember.

**To Reproduce**
1. Go to Manage > Community > News (submitnews.php)
2. Create a post with the following content:

```
With today’s V5.2 release, we enabled progression features and beaten game awards, which has been a giant team effort months in the making. <a href="https://retroachievements.org/viewtopic.php?t=24464>Click here to learn more.</a>
```

Note the missing end quote in the href attribute.

**Expected behavior**
Either it should not be possible to submit invalid HTML, or if the example above is submitted, it should render in the post as a raw string.

Generally, only anchor tags are used in news posts.

**Screenshots**
![Screenshot 2024-01-09 at 6 53 02 PM](https://github.com/RetroAchievements/RAWeb/assets/3984985/6af3aba4-78de-4dbd-98b9-9bb4df447967)

**Comment by MSGoodman** [comment] 2024-01-10 06:12
A few thoughts/questions on this one, if you don't mind:

1. Who are the users that add news items to this page? Do they know HTML? Are they manually adding in `<br>` tags here? Do they know markdown?
2. Right now we just render whatever the heck is in the news item's payload, arbitrary javascript and all, in `carousel-item.blade.php` (`{!! $news->Payload !!}`), which is scary and clearly the cause of this. We _could_ just display the raw text entered in. It sounds like you were thinking of instead selectively stripping out any non-anchor-tag HTML. I suspect this might be... painful.
3. What are your thoughts about just ripping the bandaid off and moving this to markdown?

**Comment by wescopeland** [comment] 2024-01-10 15:31
> Who are the users that add news items to this page? Do they know HTML? Are they manually adding in <br> tags here? Do they know markdown?

Any user with the Developer role or higher. They probably don't know markdown (yet). I'm not sure if they're manually adding in `<br>` tags but IMO we shouldn't support it. Some recent news posts have contained small novels - for items in a carousel this should be strongly discouraged, likely enforced via a max character limit.

> Right now we just render whatever the heck is in the news item's payload, arbitrary javascript and all, in carousel-item.blade.php ({!! $news->Payload !!}), which is scary and clearly the cause of this. We could just display the raw text entered in. It sounds like you were thinking of instead selectively stripping out any non-anchor-tag HTML. I suspect this might be... painful.

My preference would be to not support any HTML tags at all, however, a lot of news posts do contain hyperlinks to other things, and we may need to support that for backwards compatibility. Honestly, I really don't like how much flexibility we let people have in these news blurbs. It's kinda nuts. 

My true opinion is the input should support only text in these - period. This would also enforce only one `href` per post.

We could gradually adopt this - detect any post with a `<` character and throw a validation error. This would allow old posts to temporarily remain for backwards compatibility, but new posts wouldn't have the problem. Once all the old posts have rolled off after a month or so, we could stop dangerously rendering HTML.

> What are your thoughts about just ripping the bandaid off and moving this to markdown? (Happy to do that)

Love markdown, but right now it doesn't fit the UX neatly. I think the way to go would be plain text in these news blurbs and the _forum_ supporting markdown. This seems highly desirable. Ultimately we'll likely have a full-blown news section on the site, but the current gap from here to there seems quite wide.

**Comment by wescopeland** [comment] 2024-01-29 17:38
With a release containing enhanced site roles being imminent, I'm going to tackle this as part of an effort to clean up the site news UX.

**Closed** 2024-02-11 01:26 UTC
Labels: kind/bug, where/home
