### ISSUE TITLE
Code notes not showing up

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#268] opened 2019-01-21 05:18 UTC
It seems that short code notes do not show up on the Web interface, even though they are loaded correctly in the Memory Inspector on reload. I noticed it happening with notes simply labelled "HP" and "MP". 3-character notes appear correctly, so I assume the shorter ones are pruned for some reason.

**Comment by kdecks** [comment] 2019-01-21 14:57
I believe there is a minimum character requirement. My guess is about 6 characters

**Comment by ScottFromDerby** [comment] 2019-01-21 16:54
I think it's 2, because at one point I was using "" as an "empty" code note

**Comment by kdecks** [comment] 2019-01-21 17:40
I think this can be closed, unless @rzumer or @Keltron3030 disagree.

**Comment by rzumer** [comment] 2019-01-21 17:41
The issue has not been addressed at all, so I disagree.

**Comment by kdecks** [comment] 2019-01-21 17:42
I'm calling it a non-issue. It's behaving as designed.

**Comment by rzumer** [comment] 2019-01-21 17:45
The issue clearly states that 2-character strings are not displayed, and @ScottFromDerby states that the minimum string length is 2. There is clearly an error. Please allow someone to look at it instead of closing the issue due to your personal preference.

**Comment by kdecks** [comment] 2019-01-21 17:45
I didn't close it.

**Comment by luchaos** [comment] 2019-01-21 17:54
https://github.com/RetroAchievements/RAWeb/blob/develop/lib/dynrender.php#L3282
i can't determine yet whether removing that check would result in a lot of garbage output

**Comment by Keltron3030** [comment] 2019-01-21 17:55
If I understand correctly Scott said he used to have "" as an address without a note so the web would have shown every address if there wasn't a filter to eliminate two character notes.  If two or even one character notes can be displayed now without a problem it seems the web interface should allow it.

**Comment by kdecks** [comment] 2019-01-21 18:00
It will result plenty of garbage. I'm certain of it. Lots of ``''``.

**Comment by luchaos** [comment] 2019-01-21 18:05
```
SELECT * FROM CodeNotes WHERE CHAR_LENGTH(Note) = 0; -- 6201
SELECT * FROM CodeNotes WHERE CHAR_LENGTH(Note) = 1; -- 348
SELECT * FROM CodeNotes WHERE CHAR_LENGTH(Note) = 2; -- 6349
SELECT * FROM CodeNotes WHERE Note = "''"; -- 5992
```
Of 6349 two-character entries 5992 are `''`
How about we blank the `''` ones and display everything that is non-empty?
I need confirmation that `''` is not submitted through the tools, at least on the API side it doesn't look like that's happening anymore. @ScottFromDerby , what do you think?

**Comment by rzumer** [comment] 2019-01-21 18:06
Thank you for checking. Could you also check how many 1-character notes are `"`?

**Comment by Keltron3030** [comment] 2019-01-21 18:06
If they are definitely garbage then maybe they can be removed en-masse.  I don't see the value of an unlabeled note since the function would still need to be researched in order to label properly.

**Comment by luchaos** [comment] 2019-01-21 18:09
updated results @rzumer

**Comment by Jamiras** [comment] 2019-01-21 18:15
The client only ignores empty notes (and does not submit empty notes). So if two single quotes is sent to the client, the address will be selectable with a note containing two single quotes.

It doesn't make any sense as a note, so I think it's fine to nuke 'em.

**Comment by rzumer** [comment] 2019-01-21 18:15
Clearing at least the empty and `''` notes and removing the limit (or lowering it to 2) seems good to me.

**Comment by ScottFromDerby** [comment] 2019-01-21 19:22
It was laziness on my part for not writing the proper db side to allow you to *actually* delete code notes. Sorry 😇 imo all the existing empty strings can be nuked, and the site updated to show all code notes.

**Closed** 2019-01-21 19:41 UTC
Labels: enhancement, frontend

**Comment by luchaos** [comment] 2019-01-21 19:47
I think it's fine to not have any means to delete code notes for now as we'd probably want to have that in a proper audit log and soft deleted.
Also, a threaded approach to notes on the same address would be nice (?) but that's for another issue.

**Comment by Jamiras** [comment] 2019-01-21 21:51
> Edit: I think (it used to) respond to the delete button in the app by posting an "update code note" message with an empty string as the parameter

Still does.

**Comment by luchaos** [comment] 2019-01-22 03:04
i misunderstood - sorry. deletion by sending empty string now works again
