### ISSUE TITLE
Resetting all achievements for a game adjusts points incorrectly.

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#296] opened 2019-05-18 16:01 UTC
This is something I've experienced on more than one occasion. The steps to reproduce are kind of vague because I only think about it after it happens.

In this case, I started the day out at ~110028 points (capture from a tab I still had open): 
![image](https://user-images.githubusercontent.com/32680403/57971899-6082af80-7951-11e9-9442-579150e0d600.png)

Then I attempted the AotW: https://retroachievements.org/Achievement/70295

After giving up, I had three achievements for the game (2x 5 points, and 1x 10 points = 20 points + 20 points for hardcore). Therefore, my score would have been at least 110068.

Deciding I wanted to wipe the game from my history (to eliminate the measly 15% completion), I reset all achievements for the game, and suddenly my score is now 109442: 
![image](https://user-images.githubusercontent.com/32680403/57971931-af304980-7951-11e9-85fe-8fe708f073cf.png)

Instead of losing the 40 points I expected to lose, I lost over 600 points. I don't know how to explain this discrepency. I suspect it's somehow related to the calculation of `pointsToRemove` here: https://github.com/RetroAchievements/RAWeb/blob/36288f5017f4ffacd0bc56095d2a59ad912fb58d/lib/database/achievement.php#L916
but I would expect `recalcScore` (https://github.com/RetroAchievements/RAWeb/blob/a2c778e496f231ee4d4c9c19a8a996e45f028f30/public/requestresetachievements.php#L40) to overwrite any adjustments made by `pointsToRemove`

Manually activating the "Recalculate My Score" feature from my settings page, the value remains at 109442, suggesting `recalcScore` to be behaving correctly.

This implies that I somehow earned extra points from "something" that weren't seen by the `recalcScore` query, or that resetting this one game also reset something other than the achievements associated to this one game.

For completeness, I re-earned two achievements for the game, bringing my score back up to 109472: 
![image](https://user-images.githubusercontent.com/32680403/57972093-56fa4700-7953-11e9-9a5d-e441e905d35e.png)

Then reset the game again. My score returned to 109442, further suggesting that the extra points I lost were not associated to this game.

**Comment by Thoooreau** [comment] 2019-05-18 18:17
Couldn't this discrepancy be explained by some achievements from another games being demoted or having their points rearranged in this meantime?

**Comment by Jamiras** [comment] 2019-05-18 18:21
At the exact time I reset a game? Unlikely. Also, 600+ points seems like it would be more than one set having its points readjusted. 

I have seen my score drop day-to-day when announced revisions have occurred. Depending on how frequently the cron job runs (if at all) and whether or not adjusting points updates existing player scores, I suppose it's possible. 

In any case, there's evidence that _something_ isn't getting updated correctly.

**Comment by Thoooreau** [comment] 2019-05-18 18:49
You started the day with ~110028 points, then earned 40 points so you should have ~110068 points. Then you reset and had 109442 points, meaning you lost ~626 points.

I just checked in the #core-set-log and 16 hours ago 303 points from the Superman 64 set (http://retroachievements.org/game/10310) were demoted to unofficial. I know you never played this game on RA, but this 303 x2 (for hardcore) makes 606.

Maybe this is related somehow?

**Comment by Jamiras** [comment] 2021-08-05 03:48
I've come to believe that this is a side-effect of forcing a recalculation when resetting achievements. Manually doing a "Recalculate My Score" at this point would have likely also dropped my score as reported.

The player score increases every time an achievement is unlocked, but only decreases when a recalculation is performed. In addition to doing it manually, or when resetting achievements, it seems to happen about once a month. The problem most likely lies in rescores not immediately updating player scores for players who have previously unlocked the rescored achievement(s).

**Comment by Tsearo** [comment] 2022-04-29 23:15
Can this be closed or is there a different expected behavior? I'm also under the understanding that resetting any achievements recalculates the players score which can be out of sync based on things like demotes and rescores so resetting achievements doesn't seem to do any incorrect calculations.

**Comment by Jamiras** [comment] 2022-04-30 23:49
I think the behavior is well described (and not exactly a bug), but it's still a bad user experience.

When I manually reset a handful of achievements, I expect the score to only be adjusted for that handful. The readjustment caused by modifying other achievements should be handled separately - ideally as soon as the related achievements are modified.

At this point, there should be very few rescores/demotions/etc, so `recalcScore` hopefully doesn't have such a drastic effect. I'm fine if you want to close it.

**Comment by Tsearo** [comment] 2022-05-01 00:31
Yeah I agree it isn't ideal by any means and can definitely be confusing but I'm not sure that handling modified achievements that way would be a good solution either at least in terms of server resources (but I'm not too familiar with performance impacts so I could be wrong). 

For example if you earn an achievement it adds to your score (and yours only) which is pretty simple and a small impact. But if someone demotes an achievement then it would need to subtract that amount from every user at that time and same with rescores which would possibly be a large amount of calls depending on the number of achievements being rescored/demoted as well as players that earned those achievements. Also repromotions would then need to start adding score back as they currently don't since the score isn't removed upon demotion

Hopefully this is something that will be better handled in V2 🙏

**Comment by luchaos** [comment] 2022-06-03 22:51
This issue only makes sense in the context of this repo, v1 - yes, v2 has better means for that but that won't happen anytime soon.
Sounds like this will be less of an issue as soon as denormalized metrics in v1 are in place.
Let's keep this issue open as a reminder to keep an eye on that or close it as we'll inevitably touch metrics and points recalculation? I'm fine with with either.

**Comment by wescopeland** [comment] 2023-11-11 18:18
Yes, this should no longer be possible as of V5.

**Closed by wescopeland** 2023-11-11 18:18 UTC
Labels: kind/bug, area/back-end
