### ISSUE TITLE
Improvements for the Ticket Manager

### ISSUE THREAD

**Issue by JuliaWolska** [RetroAchievements/RAWeb#160] opened 2018-06-05 21:24 UTC
I suggest adding new ticket closing flag: **rejected** to use with any ticket which was sent by mistake, don't contain enough information (and sender is not providing it) to resolve it. This flag could also be used when the issue is not related to any part of the achievement (image, text or code). For example sometimes players send tickets because achievement didn't register on the site because of connection problems on one of the sides.

**Comment by kdecks** [comment] 2018-06-06 01:10
All for this. I'd like flesh out the idea too. More info will make resolving, reviewing, and sorting easier.

## Potential Ticket Statuses
- `` Open``
- ``Demoted`` (renamed from ``Closed``)
- ``Resolved (Fixed)`` (renamed from ``Resolved``)
- ``Resolved (User Error)``
- ``Work-In-Progress``
- ``Open (Unable to reproduce)``
- ``Closed (Unable to reproduce)``
- ``Open (Duplicate)``
- ``Closed (Duplicate)``
- ``Closed (Not enough Information)``

What else?

**Comment by meleu** [comment] 2018-06-06 14:18
Alright fellows, I'll try to focus on this in the next days. Let's use this issue to talk about improvements to be done on the current ticketmanager...

## Allowing tickets to be reopened (#161)

Totally agree with it. I want to make this option available for devs, admins and the reporter. Also, I'll make the system add a comment when a ticket is reopened and who reopened it.


## Adding new statuses

As a big fan of the KISS principle, I think we can handle all situations using the currently available statuses.

I'll just make the system ask the user who is closing the ticket the reason of this action and provide some options to let he/she simply select the reason. Examples:

- `Achievement Demoted`
- `Not enough information`
- `Unable to reproduce`
- `Wrong ROM` (hopefully this will be increasingly rare after the hardwork done by @rvidal77, aka caricatur)
- `Network problems`

I'll also make the system automatically add a comment saying something like:

> **`DeveloperName`** closed this ticket and gave this reason: **`Selected Reason`**

Anything more complex than that I would prefer to implement after launching RAWeb 2.0.

**Comment by kdecks** [comment] 2018-06-06 19:26
If you'd like it to be as simple as possible at least have the statuses:
- Open
- Work-In-Progress
- Closed (No fix)
- Resolved

@meleu, a few of us could come up with all the most common cases for closing tickets. Would that be helpful?

**Comment by meleu** [comment] 2018-06-06 20:04
> - Open
> - Work-In-Progress
> - Closed (No fix)
> - Resolved

In other words: you're suggesting to add the `Work-In-Progress` status, right? If it means that a dev said he/she is working to fix that ticket, it implies that the ticket is actually open, then the status should be "Open". IMO if a dev wanna say he/she is taking care of a ticket, a good approach is simply add a comment on the respective ticket.

Regardless, I want to avoid adding more complexity to the code for now because it would require adding more logic to deal with the database, creating filters, new sorting methods, etc. This is not a big problem, but I really want to spend more time learning Laravel and helping luchaos to make the RAWeb 2.0 a reality.

I just want to implement the improvements I said above because:

1. they are not that hard to implement and seems to be very useful.

2. they don't change anything about how the PHP code interacts with the database.

3. I've added links to the ticket manager in several parts of the site and increased its visibility. Now I'm noticing that more people are working on tickets. Those improvements are part of an attempt to prevent people from making a mess.

> @meleu, a few of us could come up with all the most common cases for closing tickets. Would that be helpful?

Yes, please.

**Comment by meleu** [comment] 2018-06-06 21:54
> Right now, closed also demotes.

Actually it's the other way around, when clicking in "Demote to Unofficial" it also closes the ticket. My intention is to add other ways to close, and also add more info about the reason.

I hope you also understand where I'm going to. :sweat_smile:

**Comment by kdecks** [comment] 2018-06-06 21:57
Yes

**Comment by meleu** [comment] 2018-06-07 13:50
Just a heads up about the "close ticket" feature... I'm adding these reasons for closing a ticket:

- `Achievement Demoted`
- `Not enough information`
- `Wrong ROM`
- `Network problems`

Initially I thought about adding the `Unable to reproduce` option, but I think it's too vague and also opens a door for sloppy devs use this option quite frequently to reduce their tickets.

If the user didn't provide the steps to reproduce the issue and the dev is confident that his/her code is fine, close as `Not enough information` (and add more comments if it's needed).

If the user submitted a mistaken report which the reason doesn't fit in any of the reasons above, let's just close the ticket as fixed (and add more comments if it's needed).

**Comment by kdecks** [comment] 2018-06-07 18:23
Brainstorming:

### Reasons for Resolved:
- ``Unstable address(es)``, found stable ones
- ``Needed more (stricter) conditions``
- ``No fix. Player error`` (Wrong ROM and network problems, and also mis-reports, like if they didn't actually meet the requirements correctly could be moved to here)
- ``Mistake(s) in code``
- ``Re-coded from the ground up``

I'll add to this list as I come up with more common cases.

**Closed** 2018-06-11 22:43 UTC
Labels: enhancement, tickets
