### ISSUE TITLE
Changes to the Achievement List

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#71] opened 2018-02-19 01:13 UTC
Edit: 
Rewrite: 7 April 2018

[Achievements List](http://retroachievements.org/achievementList.php?s=17)

1. **Add a column** to the Achievements List page that **display the achievement author**.
   - This makes it clear who is adding achievements without needing to go into each achievement one-by-one.
2. **Remove Unofficial Achievements from being displayed** by default on the New Achievements section of the home page. Only display to Core (Official) Achievements, Right now they show Unofficial achievements as soon as they are added.
![image](https://user-images.githubusercontent.com/32706333/38462024-5bf244fc-3a9c-11e8-8504-bcb42db2e16c.png)
   - This will prevent any confusion especially for newer players, and those who are not developers.
3. **Add a filter** on the Achievement List to display games **by filter Achievement Group**: ``Core (Official)``, ``Unofficial``. We anticipate adding other groups to this list (``WIP``, ``Garbage``, ``Demoted``, ``Bonus``) as well but that's another issue. #105, [RASuite #74](https://github.com/RetroAchievements/RASuite/issues/74) (Restructuring of Active Achievements Groups, New Achievement Groups)
   - This will allow for especially devs and above, but anyone, to be able to see which achievements fall in each Achievement Group

**Comment by ScottFromDerby** [comment] 2018-02-19 10:09
To clarify - what's the intended behaviour? Is it that it shows it but it shouldn't, or that it doesn't show it and it should?

**Comment by GameDragon2k** [comment] 2018-02-19 10:14
@ScottFromDerby 
I don't think the issue title is clear enough. What I *believe* he's asking for is another column to display the achievement author, as well as a way to indicate if the achievement is in Core or Unofficial set.

I think the inline tooltips might work for this information too, since it could be used on other pages besides just this one.

**Comment by kdecks** [comment] 2018-02-19 10:38
I get you.

**Comment by kdecks** [comment] 2018-02-19 10:46
GameDragon is correct. And I'll retitle it. If you have other directions on how we can present ideas, issues, problems and bugs more effectively please mention them.

**Comment by Jamiras** [comment] 2018-03-01 02:46
I was about to write a few lines about how this additional information would be clutter on the achievement list for the average user. Then i realized you were referring to the "New Achievements" list, not the achievement list on a game page.

I definitely agree with having a Core/Unofficial indicator, or maybe even just limiting the list to Core achievements. Unofficial achievements aren't normally meant for public consumption, so broadcasting their availability may not be desirable.

**Comment by kdecks** [comment] 2018-03-01 14:17
Good point

**Comment by kdecks** [comment] 2018-04-08 03:25
I've rewritten the top post

**Comment by meleu** [comment] 2018-05-24 15:08
the latest tweaks I made on achievementList.php implemented what is was requested by @kdecks in the OP. Closing this issue.

If you have more ideas/requests open another issue, please.

**Closed by meleu** 2018-05-24 15:08 UTC
Labels: enhancement, site pages
